go_import_path: github.com/minio/minio
sudo: required

dist: trusty

language: go

os:
- linux

env:
- ARCH=x86_64
- ARCH=i686

script:
- make
- make test GOFLAGS="-race -v"
- make coverage

after_success:
- bash <(curl -s https://codecov.io/bash)

go:
- 1.7.4
