sudo: required
dist: trusty
language: go

os:
- linux
- osx

osx_image: xcode7.2

env:
- ARCH=x86_64
- ARCH=i686

script:
- make test GOFLAGS="-race"
- make coverage

after_success:
- bash <(curl -s https://codecov.io/bash)

go:
- 1.6.2
