go_import_path: github.com/minio/minio
sudo: required

services:
 - docker

dist: trusty

language: go

os:
- linux

env:
- ARCH=x86_64

script:
## Run all the tests
- make
- diff -au <(gofmt -d cmd) <(printf "")
- diff -au <(gofmt -d pkg) <(printf "")
- make test GOFLAGS="-timeout 15m -race -v"
- make coverage

after_success:
- bash <(curl -s https://codecov.io/bash)

go:
- 1.9.4
