version: '3.7'

# starts 4 docker containers running minio server instances. Each
# minio server's web interface will be accessible on the host at port
# 9001 through 9004.
services:
  minio1:
    image: minio/minio:RELEASE.2019-08-21T19-40-07Z
    volumes:
      - data1:/data
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio1/data http://minio2/data http://minio3/data http://minio4/data 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://minio1:9000/minio/health/live"]
      interval: 1m30s
      timeout: 20s
      retries: 3
      start_period: 3m

  minio2:
    image: minio/minio:RELEASE.2019-08-21T19-40-07Z
    volumes:
      - data2:/data
    ports:
      - "9002:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio1/data http://minio2/data http://minio3/data http://minio4/data 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://minio2:9000/minio/health/live"]
      interval: 1m30s
      timeout: 20s
      retries: 3
      start_period: 3m

  minio3:
    image: minio/minio:RELEASE.2019-08-21T19-40-07Z
    volumes:
      - data3:/data
    ports:
      - "9003:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio1/data http://minio2/data http://minio3/data http://minio4/data 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://minio3:9000/minio/health/live"]
      interval: 1m30s
      timeout: 20s
      retries: 3
      start_period: 3m

  minio4:
    image: minio/minio:RELEASE.2019-08-21T19-40-07Z
    volumes:
      - data4:/data
    ports:
      - "9004:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio1/data http://minio2/data http://minio3/data http://minio4/data 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://minio4:9000/minio/health/live"]
      interval: 1m30s
      timeout: 20s
      retries: 3
      start_period: 3m

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  data1:
  data2:
  data3:
  data4:

