blank_issues_enabled: false
contact_links:
  - name: MinIO Community Support
    url: https://slack.min.io
    about: Join here for Community Support
  - name: MinIO SUBNET Support
    url: https://min.io/pricing
    about: Join here for Enterprise Support
