apiVersion: v1
description: Multi-Cloud Object Storage
name: minio
version: 5.0.15
appVersion: RELEASE.2023-09-30T07-02-29Z
keywords:
  - minio
  - storage
  - object-storage
  - s3
  - cluster
home: https://min.io
icon: https://min.io/resources/img/logo/MINIO_wordmark.png
sources:
- https://github.com/minio/minio
maintainers:
- name: MinIO, Inc
  email: dev@minio.io
