apiVersion: v1
description: Multi-Cloud Object Storage
name: minio
version: 5.2.0
appVersion: RELEASE.2022-10-24T18-35-07Z
keywords:
  - minio
  - storage
  - object-storage
  - s3
  - cluster
home: https://min.io
icon: https://min.io/resources/img/logo/MINIO_wordmark.png
sources:
- https://github.com/minio/minio
- https://github.com/ubbleai/minio
maintainers:
- name: MinIO, Inc
  email: dev@minio.io
- name: Ubble
  email: dev@ubble.ai
