apiVersion: v1
description: Multi-Cloud Object Storage
name: minio
version: 3.6.5
appVersion: RELEASE.2022-04-12T06-55-35Z
keywords:
  - minio
  - storage
  - object-storage
  - s3
  - cluster
home: https://min.io
icon: https://min.io/resources/img/logo/MINIO_wordmark.png
sources:
- https://github.com/minio/minio
maintainers:
- name: MinIO, Inc
  email: dev@minio.io
