apiVersion: v1
description: Multi-Cloud Object Storage
name: minio
version: 5.0.10
appVersion: RELEASE.2023-04-28T18-11-17Z
keywords:
  - minio
  - storage
  - object-storage
  - s3
  - cluster
home: https://min.io
icon: https://min.io/resources/img/logo/MINIO_wordmark.png
sources:
- https://github.com/minio/minio
maintainers:
- name: MinIO, Inc
  email: dev@minio.io
