apiVersion: v1
description: High Performance Object Storage
name: minio
version: 5.3.0
appVersion: RELEASE.2024-04-18T19-09-19Z
keywords:
  - minio
  - storage
  - object-storage
  - s3
  - cluster
home: https://min.io
icon: https://min.io/resources/img/logo/MINIO_wordmark.png
sources:
- https://github.com/minio/minio
maintainers:
- name: MinIO, Inc
  email: dev@minio.io
