concurrency:
  group: minio-multi-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
  

name: minio image build
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - develop
      - release/*
      - feature/*
      - feat/*
  release:
    types: [published]
jobs:
  multi-build:
    defaults:
      run:
        shell: bash
    container:
      image: soxhub/docker-ci:latest
    runs-on: self-hosted
    environment: main
    steps:
      - uses: actions/checkout@v2
        name: Checkout the repository

      - name: Quay login
        run: |
          echo "${{secrets.QUAY_TOKEN}}" | docker login --username "${{secrets.QUAY_USERNAME}}"  --password-stdin quay.io
          
      - name: Build minio
        run: bash docker-buildx.sh
